// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwr5iRTsTLD9O0mzU_CLYFmn0PLWM2Ucw',
    appId: '1:131190879848:web:dc722023b950687d122ddd',
    messagingSenderId: '131190879848',
    projectId: 'my-wallet-2ca87',
    authDomain: 'my-wallet-2ca87.firebaseapp.com',
    storageBucket: 'my-wallet-2ca87.firebasestorage.app',
    measurementId: 'G-88BCS00N7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0tDWT6HXg19bub_8xucmdAcsWLC03pNo',
    appId: '1:131190879848:android:4d38bfb1955e6a05122ddd',
    messagingSenderId: '131190879848',
    projectId: 'my-wallet-2ca87',
    storageBucket: 'my-wallet-2ca87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7-vXp6IBX0QfhF7SsDRZ8cvRcMVrEjFg',
    appId: '1:131190879848:ios:76eb637499df262f122ddd',
    messagingSenderId: '131190879848',
    projectId: 'my-wallet-2ca87',
    storageBucket: 'my-wallet-2ca87.firebasestorage.app',
    iosBundleId: 'com.example.myWallrt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7-vXp6IBX0QfhF7SsDRZ8cvRcMVrEjFg',
    appId: '1:131190879848:ios:76eb637499df262f122ddd',
    messagingSenderId: '131190879848',
    projectId: 'my-wallet-2ca87',
    storageBucket: 'my-wallet-2ca87.firebasestorage.app',
    iosBundleId: 'com.example.myWallrt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwr5iRTsTLD9O0mzU_CLYFmn0PLWM2Ucw',
    appId: '1:131190879848:web:4541bf82635f6b47122ddd',
    messagingSenderId: '131190879848',
    projectId: 'my-wallet-2ca87',
    authDomain: 'my-wallet-2ca87.firebaseapp.com',
    storageBucket: 'my-wallet-2ca87.firebasestorage.app',
    measurementId: 'G-ZCM51JDK40',
  );
}
